operator:
  # image of community-operator-v2
  image: "zufardhiyaulhaq/community-operator-v2"
  # tag of community-operator-v2 image
  tag: "v1.0.0"
  # number of replica for deployment
  replica: 1

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 20Mi
