# permissions for end users to edit announcements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: announcement-editor-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - announcements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - announcements/status
  verbs:
  - get
