# permissions for end users to view announcements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: announcement-viewer-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - announcements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - announcements/status
  verbs:
  - get
