# permissions for end users to view communities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: community-viewer-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - communities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - communities/status
  verbs:
  - get
