# permissions for end users to view telegramhandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegramhandler-viewer-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - telegramhandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - telegramhandlers/status
  verbs:
  - get
