# permissions for end users to view twitterhandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twitterhandler-viewer-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - twitterhandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - twitterhandlers/status
  verbs:
  - get
