# permissions for end users to view weeklies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weekly-viewer-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - weeklies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - weeklies/status
  verbs:
  - get
