# permissions for end users to edit weeklies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weekly-editor-role
rules:
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - weeklies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - community.zufardhiyaulhaq.com
  resources:
  - weeklies/status
  verbs:
  - get
