//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Community) DeepCopyInto(out *Community) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Community.
func (in *Community) DeepCopy() *Community {
	if in == nil {
		return nil
	}
	out := new(Community)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Community) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityList) DeepCopyInto(out *CommunityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Community, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityList.
func (in *CommunityList) DeepCopy() *CommunityList {
	if in == nil {
		return nil
	}
	out := new(CommunityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommunityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunitySpec) DeepCopyInto(out *CommunitySpec) {
	*out = *in
	in.SocialMedia.DeepCopyInto(&out.SocialMedia)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunitySpec.
func (in *CommunitySpec) DeepCopy() *CommunitySpec {
	if in == nil {
		return nil
	}
	out := new(CommunitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunitySpec_SocialMedia) DeepCopyInto(out *CommunitySpec_SocialMedia) {
	*out = *in
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Twitter != nil {
		in, out := &in.Twitter, &out.Twitter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunitySpec_SocialMedia.
func (in *CommunitySpec_SocialMedia) DeepCopy() *CommunitySpec_SocialMedia {
	if in == nil {
		return nil
	}
	out := new(CommunitySpec_SocialMedia)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityStatus) DeepCopyInto(out *CommunityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityStatus.
func (in *CommunityStatus) DeepCopy() *CommunityStatus {
	if in == nil {
		return nil
	}
	out := new(CommunityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandler) DeepCopyInto(out *TelegramHandler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandler.
func (in *TelegramHandler) DeepCopy() *TelegramHandler {
	if in == nil {
		return nil
	}
	out := new(TelegramHandler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelegramHandler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandlerList) DeepCopyInto(out *TelegramHandlerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelegramHandler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandlerList.
func (in *TelegramHandlerList) DeepCopy() *TelegramHandlerList {
	if in == nil {
		return nil
	}
	out := new(TelegramHandlerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelegramHandlerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandlerSpec) DeepCopyInto(out *TelegramHandlerSpec) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(TelegramHandlerSpec_Authentication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandlerSpec.
func (in *TelegramHandlerSpec) DeepCopy() *TelegramHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(TelegramHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandlerSpec_Authentication) DeepCopyInto(out *TelegramHandlerSpec_Authentication) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TelegramHandlerSpec_Authentication_Token)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandlerSpec_Authentication.
func (in *TelegramHandlerSpec_Authentication) DeepCopy() *TelegramHandlerSpec_Authentication {
	if in == nil {
		return nil
	}
	out := new(TelegramHandlerSpec_Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandlerSpec_Authentication_Token) DeepCopyInto(out *TelegramHandlerSpec_Authentication_Token) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandlerSpec_Authentication_Token.
func (in *TelegramHandlerSpec_Authentication_Token) DeepCopy() *TelegramHandlerSpec_Authentication_Token {
	if in == nil {
		return nil
	}
	out := new(TelegramHandlerSpec_Authentication_Token)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramHandlerStatus) DeepCopyInto(out *TelegramHandlerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramHandlerStatus.
func (in *TelegramHandlerStatus) DeepCopy() *TelegramHandlerStatus {
	if in == nil {
		return nil
	}
	out := new(TelegramHandlerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwitterHandler) DeepCopyInto(out *TwitterHandler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwitterHandler.
func (in *TwitterHandler) DeepCopy() *TwitterHandler {
	if in == nil {
		return nil
	}
	out := new(TwitterHandler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TwitterHandler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwitterHandlerList) DeepCopyInto(out *TwitterHandlerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TwitterHandler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwitterHandlerList.
func (in *TwitterHandlerList) DeepCopy() *TwitterHandlerList {
	if in == nil {
		return nil
	}
	out := new(TwitterHandlerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TwitterHandlerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwitterHandlerSpec) DeepCopyInto(out *TwitterHandlerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwitterHandlerSpec.
func (in *TwitterHandlerSpec) DeepCopy() *TwitterHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(TwitterHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwitterHandlerStatus) DeepCopyInto(out *TwitterHandlerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwitterHandlerStatus.
func (in *TwitterHandlerStatus) DeepCopy() *TwitterHandlerStatus {
	if in == nil {
		return nil
	}
	out := new(TwitterHandlerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Weekly) DeepCopyInto(out *Weekly) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Weekly.
func (in *Weekly) DeepCopy() *Weekly {
	if in == nil {
		return nil
	}
	out := new(Weekly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Weekly) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklyList) DeepCopyInto(out *WeeklyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Weekly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklyList.
func (in *WeeklyList) DeepCopy() *WeeklyList {
	if in == nil {
		return nil
	}
	out := new(WeeklyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeeklyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklySpec) DeepCopyInto(out *WeeklySpec) {
	*out = *in
	if in.Community != nil {
		in, out := &in.Community, &out.Community
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklySpec.
func (in *WeeklySpec) DeepCopy() *WeeklySpec {
	if in == nil {
		return nil
	}
	out := new(WeeklySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklySpec_Article) DeepCopyInto(out *WeeklySpec_Article) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklySpec_Article.
func (in *WeeklySpec_Article) DeepCopy() *WeeklySpec_Article {
	if in == nil {
		return nil
	}
	out := new(WeeklySpec_Article)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklySpec_Spec) DeepCopyInto(out *WeeklySpec_Spec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Articles != nil {
		in, out := &in.Articles, &out.Articles
		*out = make([]WeeklySpec_Article, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklySpec_Spec.
func (in *WeeklySpec_Spec) DeepCopy() *WeeklySpec_Spec {
	if in == nil {
		return nil
	}
	out := new(WeeklySpec_Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklyStatus) DeepCopyInto(out *WeeklyStatus) {
	*out = *in
	in.Details.DeepCopyInto(&out.Details)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklyStatus.
func (in *WeeklyStatus) DeepCopy() *WeeklyStatus {
	if in == nil {
		return nil
	}
	out := new(WeeklyStatus)
	in.DeepCopyInto(out)
	return out
}
